/** GENERATED by scripts/gen-machine-ai-frames.py — do not edit. 9-slice sheets in public/machine-ai/. */
export const MACHINE_AI_V = 1;

export interface MachineAiMeta {
  /** sheet size (px) of the full-res WebP; `-m` is half size */
  sheet: [number, number];
  /** corner slice insets (px, full-res): top right bottom left */
  slice: [number, number, number, number];
  /** visible band thickness per side (px, full-res) */
  band: [number, number, number, number];
  /** corner ornament intrusion past the band (px): the reel window is inset by band + this */
  intrusion: number;
  /** glint anchor in the corner box (0…1) */
  gem: [number, number];
  bytes: { hi: number; m: number };
}

export const MACHINE_AI: Record<string, MachineAiMeta> = {
  kredit: { sheet: [546, 505], slice: [132, 158, 153, 127], band: [101, 138, 133, 107], intrusion: 14, gem: [0.487, 0.463], bytes: { hi: 64232, m: 20118 } },
  sloboda: { sheet: [614, 562], slice: [142, 185, 200, 189], band: [108, 147, 156, 151], intrusion: 28, gem: [0.608, 0.5], bytes: { hi: 69420, m: 23458 } },
  smart: { sheet: [596, 543], slice: [158, 176, 165, 180], band: [78, 90, 82, 88], intrusion: 62, gem: [0.488, 0.567], bytes: { hi: 54026, m: 18128 } },
  telka: { sheet: [558, 528], slice: [160, 179, 128, 179], band: [104, 115, 73, 114], intrusion: 44, gem: [0.594, 0.676], bytes: { hi: 53744, m: 20536 } },
  optika: { sheet: [565, 543], slice: [156, 162, 167, 163], band: [110, 107, 110, 109], intrusion: 32, gem: [0.499, 0.588], bytes: { hi: 70762, m: 21320 } },
  duo: { sheet: [541, 539], slice: [149, 150, 150, 151], band: [84, 84, 82, 84], intrusion: 43, gem: [0.498, 0.522], bytes: { hi: 59268, m: 19804 } },
  fiveg: { sheet: [532, 569], slice: [162, 163, 167, 164], band: [108, 109, 107, 110], intrusion: 47, gem: [0.658, 0.696], bytes: { hi: 73494, m: 24644 } },
  nekonecno: { sheet: [831, 594], slice: [249, 301, 281, 302], band: [104, 116, 115, 118], intrusion: 33, gem: [0.385, 0.384], bytes: { hi: 123810, m: 39766 } },
};
