CREATE TABLE IF NOT EXISTS duel_rooms (
  code TEXT PRIMARY KEY,
  host_name TEXT NOT NULL,
  guest_name TEXT NOT NULL DEFAULT '',
  mode TEXT NOT NULL,
  bet DOUBLE PRECISION NOT NULL,
  phase TEXT NOT NULL DEFAULT 'wait',
  host_score DOUBLE PRECISION NOT NULL DEFAULT 0,
  host_have INT NOT NULL DEFAULT 0,
  guest_score DOUBLE PRECISION NOT NULL DEFAULT 0,
  guest_have INT NOT NULL DEFAULT 0,
  need INT NOT NULL DEFAULT 10,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);
